@startuml

autonumber
title BOOK STORE APPLICATION - SEQUENCE DIAGRAM

participant BookController as BookController
participant BookService as BookServiceImpl
participant BookRepository as BookRepositoryImpl
participant BookSerializer as BookSerializer

rnote over BookController: add(BookDTO)
activate BookController
BookController -> BookServiceImpl: add(BookDTO)
activate BookServiceImpl
rnote over BookServiceImpl: add(BookDTO)
BookServiceImpl -> BookRepositoryImpl: add(BookEntity)
activate BookRepositoryImpl
rnote over BookRepositoryImpl: add(BookEntity)
BookRepositoryImpl -> BookSerializer: serializeBook(BookEntity)
activate BookSerializer
BookRepositoryImpl <-- BookSerializer: return
deactivate BookSerializer
BookServiceImpl <-- BookRepositoryImpl: return
deactivate BookRepositoryImpl
BookController <-- BookServiceImpl: return
deactivate BookServiceImpl

@enduml
